### PR TITLE
Сompile lang files

### PR DESCRIPTION
**Pull request by na1s**
Hi.
I've just compiled lang files b/c some of them are obsolete.
Thanks

### CODE REVIEW

**Comment by mmerickel** [comment]
Thank you, could you please add your name to contributors.txt as well?

**Comment by na1s** [comment]
sure, thank you

**Comment by na1s** [comment]
done:-)

**Comment by na1s** [comment]
Should I do anything else?

**Comment by stevepiercy** [comment]
Thanks for the reminder!

**Pull request merged**
