### PR TITLE
Cleanup translations & restore German translation for 'Required'

### PR DESCRIPTION
**Pull request by mloesch**
Note: the literal string 'Required' is not marked in the code, so running  `update_catalog` will remove it from the *.po files. This probably should be fixed as well.

### CODE REVIEW

**Comment by mmerickel** [comment]
Could you please update this PR such that the extractor works on the string you mentioned?

**Comment by mmerickel** [comment]
These changes need to be rebased against the current master.

**Comment by mloesch** [comment]
@mmerickel plz review again. I did not run update_catalog as it gives me a lot of fuzzy conflicts in the translations of languages I do not speak.

**Comment by mmerickel** [comment]
So I ran `update_catalog` and got an exception because the `locale/nl/LC_MESSAGES/colander.po` file had `Language: \n` instead of `Language: nl\n`. After I solved that I got to where you are with some conflicts. I looked quickly and several of the conflicts are suggesting incorrect fixes so it's going to require a fine-grained update.

This is the first time I've ever even run `update_catalog` so I'm very much uncomfortable going through and updating these translations. I feel like I have no choice but to keep this open for now until I or hopefully someone else can go through this and sort things out.

Sorry @mloesch!

**Pull request merged**
