### PR TITLE
fix pdf rendering by removing unused .gif

### PR DESCRIPTION
**Pull request by tisdall**
It seems LaTeX doesn't support GIF files and that's what
readthedocs are using to generate the PDF versions of the docs.
So, removed the reference to the `.gif` file and deleted the unused
cruft.

### CODE REVIEW

**Comment by stevepiercy** [comment]
@tisdall thanks for this. We're also moving all Pylons docs to using https://github.com/Pylons/pylons-sphinx-themes following its documented procedure. I recently did so on https://github.com/Pylons/translationstring but I missed removing the cruft you mention here. You're welcome to jump on this task, or I can do it tonight. I'm leaving this open until one of us has the chance to work on the whole thing.

**Comment by tisdall** [comment]
I could do it tomorrow...  It's up to you.

**Comment by stevepiercy** [comment]
Thank you! I'm working on the rest of the tasks now. However, don't count on PDF generation to work. See #222.

**Comment by stevepiercy** [comment]
FWIW, PDF now does build on RTD. Yippee!

**Comment by tisdall** [comment]
unfortunately, it seems RTD has tied PDF creation with HTML creation...  if either fails the other fails too.

**Comment by stevepiercy** [comment]
Often PDF will fail to build, but HTML will build. PDF is far more particular in its build process, especially concerning any non-.jpg or -.png images. There is a feature request for RTD to make PDF building optional.

**Pull request merged**
