### PR TITLE
update translations nl

### PR DESCRIPTION
**Pull request by cahytinne**
Update of the Dutch translations: `nl`

### CODE REVIEW

**Comment by bertjwregeer** [comment]
:+1:

**Comment by bertjwregeer** [comment]
@stevepiercy :+1:

**Comment by stevepiercy** [comment]
Thanks @bertjwregeer.

@cahytinne would you please sign [CONTRIBUTORS.txt](https://github.com/Pylons/colander/blob/master/CONTRIBUTORS.txt)? You can pull in @bertjwregeer's change, then push a commit to this PR, and it will update. Then I can merge.

I'll also add a note to CHANGES.rst.

**Comment by bertjwregeer** [comment]
@stevepiercy My changes were already pulled in :-). Looks like it is ready for a merge now :-)

**Comment by stevepiercy** [comment]
Thank you both, @bertjwregeer and @cahytinne

**Pull request merged**
