### PR TITLE
Pre-joined error messages.

### PR DESCRIPTION
**Pull request by gjo**
`colander.Invalid:asdict` returns field's error messages as a single string joined with '; ' now.
this patch allows optional separators to user,
and if it supplied `None` it returns pre-joined messages as list of string.

### CODE REVIEW

**Comment by gjo** [comment]
CI build failed on Python 3.2.
But it's no problem because pip 8.0 that used on CI droped python 3.2 support.
https://github.com/pypa/pip/blob/develop/CHANGES.txt

Can I edit tox.ini, too?

**Comment by bertjwregeer** [comment]
Please merge master into your branch, and push to this PR.

Thanks.

**Comment by gjo** [comment]
Done.
Thank you @bertjwregeer

**Comment by mmerickel** [comment]
LGTM. Please add a note to the changelog referencing this PR and add your name to the CONTRIBUTORS.txt.

**Comment by gjo** [comment]
I was already added my name to CONTRIBUTORS.txt:124.
Thank you.

**Pull request merged**
