### PR TITLE
Add traditional chinese localization

### PR DESCRIPTION
**Pull request by dwt**
This pull request is in the same spirit as https://github.com/Pylons/deform/pull/340#issuecomment-288172382 . What happened is, that a user from Taiwan contacted us and provided this localization - so we would like to contribute it upstream.

As I am not a speaker/reader of chinese, it is hard for me to judge how this compares to your existing localization - I can however offer some observations. (Please also see the discussion for the deform pull request).

colander has a zh translation - which should to my understanding should be in simplified chinese (hans) script as that is read by the majority of readers. It does look to me that it is also in traditional chinese - though of course I can't be sure. If that is the case, it would be interesting to discover if it is the Hongkong dialect, as in that case, you should probably rename it it zh_Hant_HK and take in our localization as zh_Hant_TW. Also zh should probably be a localization you don't have yet as it should be zh_Hans (for simplified).

Thanks and best regards,
Martin Häcker

### CODE REVIEW

**Comment by dwt** [comment]
ping @maintainers, is there anything that prevents you from merging?

**Comment by mmerickel** [comment]
There are enough unknowns in your original statement that I'm not comfortable reviewing or merging this. I would require a native speaker to review it.

**Comment by dwt** [comment]
Well, anything I can do to help? I don't really have contacts to technical chinese speaking people though.

**Comment by mmerickel** [comment]
It looks like you're suggesting that we rename the current `zh` translation to `zh_Hans` but your current PR does not do that. I'm concerned about the implications of doing so and am thus not going to do it myself as I rarely ever need to deal with i18n so I'm concerned about accepting this PR and breaking someone's workflow unknowingly.

**Comment by mmerickel** [comment]
Okay, I consulted my coworker who was able to identify the current "zh" translation as "zh_Hans" and said that's a sane default so adding zh_Hant would be alright. I'd ask that you update this PR to add a comment to our "zh" translation specifically noting that it's simplified chinese so that we can know what we have in the future.

**Comment by dwt** [comment]
I'm not sure I get you right - the translation I sent you is in Traditional Chinese (and notes so in the file on the first line). It also has a comment that Identifies it as being from a Taiwanese localizer should this distinction get interesting in the future (e.g. when you get a traditional Chinese localization from another region).

Do you need anything else?

**Comment by tisdall** [comment]
@dwt - I think Michael is saying to add a comment to the already existing "zh" translation to indicate that it is "Hans".

However, I think it's better to move the "zh" one to "zh_Hans".  It's up to the localization software to decide which "zh" to use as a default.  If someone specifically asks for "zh" they're indicating that they have no preference between "Hans" or "Hant" and it's up to the localization to choose which one it wants to return.

**Comment by dwt** [comment]
Ah I get it. Also I agree with you about the move from zh to zh_Hans and will update the pull request accordingly.

**Comment by dwt** [comment]
@mmerickel Do these changes work for you?

**Comment by mmerickel** [comment]
Thanks @dwt

**Comment by dwt** [comment]
:-)

**Pull request merged**
