### PR TITLE
Add support for Python 3.9/3.10 to CI

### PR DESCRIPTION
**Pull request by jenstroeger**
When working on PR #348 I noticed that support for Python 3.10 is missing, and Python 3.9 is incomplete. Here’s the update.

Ubuntu’s default Python is still 3.8 so I guess we can leave that as the default Python in the CI/tox configuration. However, I’ve already removed it from my system because it _does not_ received [bug fixes any longer](https://peps.python.org/pep-0569/#lifespan).

Also, what about this `py35`…

https://github.com/Pylons/colander/blob/048fb24eeb6c3df21831413943dbf89d7b5776e4/tox.ini#L29

### CODE REVIEW

**Comment by stevepiercy** [comment]
Several of the builds fail. Lint should be easy to fix. The other failures are due to unavailable Python versions for `actions/setup-python@v1`. Try bumping that to `@v4`. See https://github.com/actions/setup-python#available-versions-of-python.

**Comment by jenstroeger** [comment]
Thanks @stevepiercy, I just saw the slew of emails come in ☺️

**Comment by stevepiercy** [comment]
Regarding support for old Pythons, let's get the opinions of the maintainers. @mcdonc @ericof @miohtama @mmerickel @tseaver 

IIRC there was some reason to continue testing on 2.7, 3.5, and 3.6, even though they are EOLed, or maybe that was another Pylons Project project.

**Comment by stevepiercy** [comment]
I changed the setting on this repo for running workflows so that I don't have to keep approving it.

https://github.com/Pylons/colander/settings/actions

Previously it was:

Require approval for first-time contributors who are new to GitHub

Now it is:

Require approval for first-time contributors

**Comment by jenstroeger** [comment]
@stevepiercy I hope you’ll squash this PR when you merge it 😉

**Comment by jenstroeger** [comment]
Alright, this worked. Happy to squash the four commits into one or you can squash it on merge?

**Review by stevepiercy — APPROVED** [review]

**Comment by stevepiercy** [comment]
Oops, too quick on my approval. I forgot that a few more files need to be updated as part of this PR.

- `setup.cfg`
- `README.rst`
- `docs/index.rst`

**Comment by jenstroeger** [comment]
> I forgot that a few more files need to be updated as part of this PR.

I’ll make those changes now. @stevepiercy, shall I squash the commits?

**Comment by stevepiercy** [comment]
Nah, don't bother squashing.

**Review by stevepiercy — APPROVED** [review]

**Comment by jenstroeger** [comment]
Thanks for approving. Once this one’s merged into `master` I’ll rebase #348 so we can move forward with that validator.

**Comment by stevepiercy** [comment]
Because no support has been removed, but new support added and old support fixed, I'm going to merge this to keep things rolling forward. Thank you!

**Pull request merged**
