### PR TITLE
Update basics.rst

### PR DESCRIPTION
**Pull request by alenajk**
Adding more gender neutral language for "developer"

### CODE REVIEW

**Comment by mmerickel** [comment]
I'd prefer to use `it is the responsibility of the developer to ensure they serialize ...` unless that is not politically correct anymore... it's my current go-to for gender neutral pronouns.

**Comment by stevepiercy** [comment]
Thank you! I also prefer the neutralization of our pronouns, y'all.

**Comment by tisdall** [comment]
Yes, I agree with @stevepiercy ... It should be changed to the following: `it is the responsibility of the developer to ensure y'all serialize "the right" data`

**Comment by stevepiercy** [comment]
Yo! I was playing with "y'all", not suggesting it. 😜  Even though I like me some Southern lilt or twang, it ain't right here.

**Pull request merged**
